In [2]:
import pandas as pd
import numpy as np

### Rows and Columns - Operations (Add, Update, Delete)

In [3]:
data = {
    'name':['Ram','Shyam','Hari'],
    'age':[16,17,18],
    'salary':[40000,50000,60000]
           
}

In [5]:
df = pd.DataFrame(data)
df

    name  age  salary
0    Ram   16   40000
1  Shyam   17   50000
2   Hari   18   60000

In [8]:
# add new column 
df['Team'] = ['CEO','HR','CTO',]
df

    name  age  salary Team
0    Ram   16   40000  CEO
1  Shyam   17   50000   HR
2   Hari   18   60000  CTO

In [11]:
df['bonus'] = df['salary'] * 0.2
df

    name  age  salary Team    bonus
0    Ram   16   40000  CEO   8000.0
1  Shyam   17   50000   HR  10000.0
2   Hari   18   60000  CTO  12000.0

In [16]:
# adding the rows
df.loc[len(df)] = ['ABC',19,70000,'EMP',1200]
df

    name  age  salary Team    bonus
0    Ram   16   40000  CEO   8000.0
1  Shyam   17   50000   HR  10000.0
2   Hari   18   60000  CTO  12000.0
3    ABC   19   70000  EMP   1200.0
4    ABC   19   70000  EMP   1200.0

In [23]:
# update value - using the index
df.loc[4,'bonus'] = 3000
df

    name  age  salary Team    bonus
0    Ram   16   40000  CEO   3000.0
1  Shyam   17   50000   HR  10000.0
2   Hari   18   60000  CTO  12000.0
3    ABC   19   70000  EMP   1200.0
4    ABC   19   70000  EMP   3000.0

In [25]:
# update value - using the name

df.loc[df.name=='Ram','salary'] = 90000
df

    name  age  salary Team    bonus
0    Ram   16   90000  CEO   3000.0
1  Shyam   17   50000   HR  10000.0
2   Hari   18   60000  CTO  12000.0
3    ABC   19   70000  EMP   1200.0
4    ABC   19   70000  EMP   3000.0

In [33]:
# delete value - row and column values

df.drop(df[df.name == 'ABC'].index,inplace=True)

In [34]:
df.drop('bonus',axis = 1)

    name  age  salary Team
0    Ram   16   90000  CEO
1  Shyam   17   50000   HR
2   Hari   18   60000  CTO

In [35]:
# sort values

df.sort_values('salary')

    name  age  salary Team    bonus
1  Shyam   17   50000   HR  10000.0
2   Hari   18   60000  CTO  12000.0
0    Ram   16   90000  CEO   3000.0

In [ ]:
# working with the date value

In [36]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28']
df

    name  age  salary Team    bonus         DOJ
0    Ram   16   90000  CEO   3000.0  2024-01-01
1  Shyam   17   50000   HR  10000.0  2024-01-15
2   Hari   18   60000  CTO  12000.0  2024-03-28

In [38]:
df['DOJ'].dtype

In [39]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [40]:
df['DOJ'].dtype

dtype('<M8[us]')

In [41]:
df1 = df

In [48]:
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025']
df1

    name  age  salary Team    bonus        DOJ        DOJ2
0    Ram   16   90000  CEO   3000.0 2024-01-01  01-01-2025
1  Shyam   17   50000   HR  10000.0 2024-01-15  15-01-2025
2   Hari   18   60000  CTO  12000.0 2024-03-28  28-03-2025

In [49]:
df1['DOJ2'].dtype

In [52]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'],format = '%d-%m-%Y')
df1

    name  age  salary Team    bonus        DOJ       DOJ2
0    Ram   16   90000  CEO   3000.0 2024-01-01 2025-01-01
1  Shyam   17   50000   HR  10000.0 2024-01-15 2025-01-15
2   Hari   18   60000  CTO  12000.0 2024-03-28 2025-03-28

In [57]:
df

    name  age  salary Team    bonus        DOJ
0    Ram   16   90000  CEO   3000.0 2024-01-01
1  Shyam   17   50000   HR  10000.0 2024-01-15
2   Hari   18   60000  CTO  12000.0 2024-03-28

In [58]:
df['DOJ'].dt.year

0    2024
1    2024
2    2024
Name: DOJ, dtype: int32

In [59]:
df['DOJ'].dt.month

0    1
1    1
2    3
Name: DOJ, dtype: int32

In [60]:
df['DOJ'].dt.day

0     1
1    15
2    28
Name: DOJ, dtype: int32

In [61]:
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
Name: DOJ, dtype: str

In [62]:
df['month'] = df['DOJ'].dt.month

In [63]:
df

    name  age  salary Team    bonus        DOJ  month
0    Ram   16   90000  CEO   3000.0 2024-01-01      1
1  Shyam   17   50000   HR  10000.0 2024-01-15      1
2   Hari   18   60000  CTO  12000.0 2024-03-28      3

In [64]:
df['DOJ'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
Name: DOJ, dtype: datetime64[us]

## Handling the missing values

In [65]:
df

    name  age  salary Team    bonus        DOJ  month
0    Ram   16   90000  CEO   3000.0 2024-01-01      1
1  Shyam   17   50000   HR  10000.0 2024-01-15      1
2   Hari   18   60000  CTO  12000.0 2024-03-28      3

In [66]:
df.isnull()

    name    age  salary   Team  bonus    DOJ  month
0  False  False   False  False  False  False  False
1  False  False   False  False  False  False  False
2  False  False   False  False  False  False  False

In [67]:
df.loc[df.name == 'Hari','salary'] = np.nan

In [68]:
df

    name  age   salary Team    bonus        DOJ  month
0    Ram   16  90000.0  CEO   3000.0 2024-01-01      1
1  Shyam   17  50000.0   HR  10000.0 2024-01-15      1
2   Hari   18      NaN  CTO  12000.0 2024-03-28      3

In [69]:
df.isnull()

    name    age  salary   Team  bonus    DOJ  month
0  False  False   False  False  False  False  False
1  False  False   False  False  False  False  False
2  False  False    True  False  False  False  False

In [71]:
df.isnull().sum()

name      0
age       0
salary    1
Team      0
bonus     0
DOJ       0
month     0
dtype: int64

In [72]:
df.fillna(0)

    name  age   salary Team    bonus        DOJ  month
0    Ram   16  90000.0  CEO   3000.0 2024-01-01      1
1  Shyam   17  50000.0   HR  10000.0 2024-01-15      1
2   Hari   18      0.0  CTO  12000.0 2024-03-28      3