# Dataframe

#### It's a structured data constructed with rows and columns, similar to a SQL tables or Excel tables

In [1]:
import pandas as pd

In [6]:
# Create Dataframe
df = pd.DataFrame([11,22,33],columns=['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [5]:
print(type(df))

<class 'pandas.DataFrame'>

In [7]:
data = {
    'name':['Ram','Shyam','Hari'],
    'age':[16,17,18],
    'salary':[40000,50000,60000]
           
}

In [9]:
df = pd.DataFrame(data)
print(df)

    name  age  salary
0    Ram   16   40000
1  Shyam   17   50000
2   Hari   18   60000

## Basic DataFrame

In [10]:
df.head(2)

    name  age  salary
0    Ram   16   40000
1  Shyam   17   50000

In [11]:
df.tail(2)

    name  age  salary
1  Shyam   17   50000
2   Hari   18   60000

In [12]:
df.shape

(3, 3)

In [13]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [15]:
df.rename(columns={'salary' : 'fortnight_Salary'},inplace='True')

In [16]:
df

    name  age  fortnight_Salary
0    Ram   16             40000
1  Shyam   17             50000
2   Hari   18             60000

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              3 non-null      str
 1   age               3 non-null      int64
 2   fortnight_Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [18]:
df.describe()

        age  fortnight_Salary
count   3.0               3.0
mean   17.0           50000.0
std     1.0           10000.0
min    16.0           40000.0
25%    16.5           45000.0
50%    17.0           50000.0
75%    17.5           55000.0
max    18.0           60000.0

In [20]:
# saving and loading the file
df.to_csv('Z:/test.csv',index=False)

In [25]:
load_df = pd.read_csv('Z:/test.csv')
load_df

    name  age  fortnight_Salary
0    Ram   16             40000
1  Shyam   17             50000
2   Hari   18             60000

## Rows & columns - Selection

In [26]:
# column selection
df[['name']]

    name
0    Ram
1  Shyam
2   Hari

In [47]:
df[['name','fortnight_Salary']]

    name  fortnight_Salary
0    Ram             40000
1  Shyam             50000
2   Hari             60000

In [34]:
# select the rows -> label based 

df.loc[df.name=='Ram']

  name  age  fortnight_Salary
0  Ram   16             40000

In [35]:
# select the rows - index value based

df.iloc[0]

name                  Ram
age                    16
fortnight_Salary    40000
Name: 0, dtype: object

In [36]:
df.iloc[0:2]

    name  age  fortnight_Salary
0    Ram   16             40000
1  Shyam   17             50000

In [42]:
# filter dataframe

age_fil = df[df['age'] > 17]
age_fil

   name  age  fortnight_Salary
2  Hari   18             60000

In [50]:
df[(df['age'] > 17) & (df['fortnight_Salary' ] > 20000)]

   name  age  fortnight_Salary
2  Hari   18             60000

In [51]:
df.where(df['age'] > 17)

   name   age  fortnight_Salary
0   NaN   NaN               NaN
1   NaN   NaN               NaN
2  Hari  18.0           60000.0

In [52]:
df.where(df['age'] > 17,other = 'not eligible')

           name           age fortnight_Salary
0  not eligible  not eligible     not eligible
1  not eligible  not eligible     not eligible
2          Hari            18            60000