In [3]:
import numpy as np
import pandas as pd

In [ ]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [9]:
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_yr'] = date['date'].dt.year

In [12]:
date.head()

        date  product_id  city_id  orders  date_yr
0 2019-12-10        5628       25       3     2019
1 2018-08-15        3646       14     157     2018
2 2018-10-23        1859       25       1     2018
3 2019-08-17        7292       25       1     2019
4 2019-01-06        4344       25       3     2019

In [13]:
date['date_month'] = date['date'].dt.month

In [14]:
date.sample(5)

          date  product_id  city_id  orders  date_yr  date_month
370 2019-01-23        4573        2       3     2019           1
836 2018-07-17        2430       23       4     2018           7
219 2019-07-26        4425       16       2     2019           7
177 2019-08-10         585       17      13     2019           8
780 2018-11-07         702        6       2     2018          11

In [15]:
date['date_name'] = date['date'].dt.month_name()

In [16]:
date.head()

        date  product_id  city_id  orders  date_yr  date_month date_name
0 2019-12-10        5628       25       3     2019          12  December
1 2018-08-15        3646       14     157     2018           8    August
2 2018-10-23        1859       25       1     2018          10   October
3 2019-08-17        7292       25       1     2019           8    August
4 2019-01-06        4344       25       3     2019           1   January

In [17]:
date['date_day'] = date['date'].dt.day

In [18]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [21]:
date['weekday_name'] = date['date'].dt.day_name()

In [22]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day,weekday,weekday_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,Sunday

In [23]:
date['weekday'] = date['date'].dt.dayofweek

In [24]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day,weekday,weekday_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [25]:
date['date_weekend'] = np.where(date['weekday'].isin([5, 6]), 1, 0)

In [26]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day,weekday,weekday_name,date_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [29]:
date['no_of_week'] = date['date'].dt.isocalendar().week

In [30]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day,weekday,weekday_name,date_weekend,no_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [31]:
date['quarter'] = date['date'].dt.quarter

In [32]:
date.head()

,date,product_id,city_id,orders,date_yr,date_month,date_name,date_day,weekday,weekday_name,date_weekend,no_of_week,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [36]:
date['semester'] = np.where(date['quarter'].isin([1, 2]), 1, 2)
date.drop(columns=['product_id','city_id','orders'], inplace=True)

In [37]:
date.head()

,date,date_yr,date_month,date_name,date_day,weekday,weekday_name,date_weekend,no_of_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [39]:
import datetime as dt

today = dt.datetime.today()
today

datetime.datetime(2026, 7, 4, 6, 45, 19, 688211)

In [40]:
today - date['date']

0     2398 days 06:45:19.688211
1     2880 days 06:45:19.688211
2     2811 days 06:45:19.688211
3     2513 days 06:45:19.688211
4     2736 days 06:45:19.688211
                 ...
995   2826 days 06:45:19.688211
996   2767 days 06:45:19.688211
997   2615 days 06:45:19.688211
998   2680 days 06:45:19.688211
999   2454 days 06:45:19.688211
Name: date, Length: 1000, dtype: timedelta64[ns]